// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as ReactNative from "react-native";

function checkAuthWithRoute(navigation) {
  return ReactNative.AsyncStorage.getItem("userToken").then((function (stringOrNull) {
                console.log("CHECKING_AUTH_TOKEN", stringOrNull);
                if (stringOrNull !== null) {
                  return Promise.resolve(navigation.push("App"));
                } else {
                  return Promise.resolve(navigation.push("SignIn"));
                }
              }));
}

function signOutAsync(navigation) {
  ReactNative.AsyncStorage.clear().then((function (_result) {
          return Promise.resolve(Promise.resolve(navigation.push("AuthLoading")));
        }));
  return /* () */0;
}

function signInAsync(navigation) {
  ReactNative.AsyncStorage.setItem("userToken", "abc").then((function (_result) {
          return Promise.resolve(Promise.resolve(navigation.push("App")));
        }));
  return /* () */0;
}

export {
  checkAuthWithRoute ,
  signOutAsync ,
  signInAsync ,
  
}
/* react-native Not a pure module */
