// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Utils from "./utils/Utils.bs.js";
import * as React from "react";
import * as GlobalStyle from "./GlobalStyle.bs.js";
import * as ReactNative from "react-native";

function SignInScreen(Props) {
  var navigation = Props.navigation;
  return React.createElement(ReactNative.View, {
              style: GlobalStyle.styles.container,
              children: React.createElement(ReactNative.Button, {
                    onPress: (function (param) {
                        return Utils.signInAsync(navigation);
                      }),
                    title: "Sign in!"
                  })
            });
}

var make = SignInScreen;

export {
  make ,
  
}
/* Utils Not a pure module */
